[package]
repository = "https://github.com/stillonearth/bevy_rl_shooter"
edition = "2021"
name = "bevy_rl_shooter"
version = "0.1.2"
license = "MIT OR Apache-2.0"
description = "ğŸ‘¾Multi-Agent ğŸ® FPS Gym Environment with ğŸ‹ï¸ bevy_rl"
keywords = ["ai", "bevy", "gym", "rl", "bevy_rl"]

[dependencies]
bevy = { version = "0.10.1" }
bevy_mod_raycast = { version = "0.8.0" }
bevy-inspector-egui = "0.18.3"
bevy_rl = { version = "0.10.2" }
bitflags = "2.3.1"
clap = { version = "4.0.2", features = ["derive"] }
crossbeam-channel = "0.5.6"
bevy_rapier3d = { version = "0.21.0", features = [
    "simd-stable",
    "debug-render",
] }
image = "0.24.1"
names = { version = "0.14.0", default-features = false }
rand = "0.8.5"
serde = "1.0.140"
serde_json = "1.0.82"

[profile.dev]
opt-level = 3
